
theme: jekyll-theme-cayman
title: Paradigms of Globlization
description: And this is the textual description of your website 
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Terms List', 'pagename': 'Terms List'}, 
{'name': 'Key Terms Frequency', 'pagename': 'Key_Words_Frequency'}, 
{'name': 'Demography : United Nations and World Bank', 'pagename': 'Demography'}, 
{'name': 'World Bank Network Map Insights', 'pagename': 'worldbankdnetworkmap'}, 
{'name': 'Epic Epoch - World Bank', 'pagename': 'EpicEpochWB'}, 
{'name': 'Demography - World Bank', 'pagename': 'WorldBankDemography'}, 
{'name': 'Visualizing International Relations', 'pagename': 'internationalrelations'},
{'name': 'Limitations', 'pagename': 'Limitations'}, 
{'name': 'Feedback', 'pagename': 'finalpage'}
]
